import { Project, User, Notification } from '@/types';

export const mockUsers: User[] = [
  {
    id: '1',
    email: 'client@example.com',
    name: 'Alex Johnson',
    role: 'client',
    avatar: undefined,
  },
  {
    id: '2',
    email: 'admin@blunicorn.org',
    name: 'Sarah Chen',
    role: 'admin',
    avatar: undefined,
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'E-commerce Order Automation',
    description: 'Automated order processing workflow connecting Shopify to inventory management and shipping providers.',
    status: 'in-progress',
    progress: 65,
    estimatedDelivery: '2025-01-20',
    clientId: '1',
    clientName: 'Alex Johnson',
    milestones: [
      {
        id: 'm1',
        title: 'Discovery & Requirements',
        description: 'Initial consultation and workflow mapping',
        status: 'completed',
        completedAt: '2025-01-02',
      },
      {
        id: 'm2',
        title: 'Core Workflow Development',
        description: 'Building the main automation workflow',
        status: 'completed',
        completedAt: '2025-01-06',
      },
      {
        id: 'm3',
        title: 'Integration Testing',
        description: 'Testing with live Shopify data',
        status: 'active',
      },
      {
        id: 'm4',
        title: 'Documentation & Handoff',
        description: 'Final documentation and client training',
        status: 'pending',
      },
    ],
    deliverables: [
      {
        id: 'd1',
        name: 'Order Processing Workflow',
        type: 'workflow',
        url: '/files/order-workflow.json',
        locked: true,
      },
      {
        id: 'd2',
        name: 'Setup Guide',
        type: 'guide',
        url: '/files/setup-guide.pdf',
        locked: true,
      },
      {
        id: 'd3',
        name: 'Video Walkthrough',
        type: 'video',
        url: 'https://loom.com/example',
        locked: true,
      },
    ],
    feedback: [
      {
        id: 'f1',
        message: 'Looks great so far! Can we add an email notification when orders fail?',
        author: 'Alex Johnson',
        createdAt: '2025-01-05T10:30:00Z',
      },
      {
        id: 'f2',
        message: 'Great suggestion! Adding that to the workflow now.',
        author: 'Sarah Chen',
        createdAt: '2025-01-05T11:45:00Z',
      },
    ],
    createdAt: '2025-01-01T00:00:00Z',
    updatedAt: '2025-01-08T09:00:00Z',
    revisionCount: 2,
  },
  {
    id: '2',
    name: 'Lead Nurturing Sequence',
    description: 'Automated email sequences based on lead behavior and engagement scoring.',
    status: 'ready',
    progress: 100,
    estimatedDelivery: '2025-01-10',
    clientId: '1',
    clientName: 'Alex Johnson',
    milestones: [
      {
        id: 'm1',
        title: 'Discovery & Requirements',
        description: 'Understanding lead journey and triggers',
        status: 'completed',
        completedAt: '2024-12-28',
      },
      {
        id: 'm2',
        title: 'Sequence Development',
        description: 'Building email automation sequences',
        status: 'completed',
        completedAt: '2025-01-03',
      },
      {
        id: 'm3',
        title: 'Testing & QA',
        description: 'Testing all trigger conditions',
        status: 'completed',
        completedAt: '2025-01-08',
      },
      {
        id: 'm4',
        title: 'Documentation',
        description: 'Complete documentation package',
        status: 'completed',
        completedAt: '2025-01-08',
      },
    ],
    deliverables: [
      {
        id: 'd1',
        name: 'Lead Nurturing Workflow',
        type: 'workflow',
        url: '/files/lead-workflow.json',
        locked: false,
      },
      {
        id: 'd2',
        name: 'Technical Documentation',
        type: 'documentation',
        url: '/files/tech-docs.pdf',
        locked: false,
      },
      {
        id: 'd3',
        name: 'Setup & Configuration Guide',
        type: 'guide',
        url: '/files/config-guide.pdf',
        locked: false,
      },
    ],
    feedback: [],
    createdAt: '2024-12-20T00:00:00Z',
    updatedAt: '2025-01-08T12:00:00Z',
    revisionCount: 1,
  },
  {
    id: '3',
    name: 'CRM Data Sync',
    description: 'Real-time bidirectional sync between HubSpot and internal database.',
    status: 'discovery',
    progress: 15,
    estimatedDelivery: '2025-02-01',
    clientId: '1',
    clientName: 'Alex Johnson',
    milestones: [
      {
        id: 'm1',
        title: 'Discovery & Requirements',
        description: 'Mapping data fields and sync rules',
        status: 'active',
      },
      {
        id: 'm2',
        title: 'Development',
        description: 'Building sync workflows',
        status: 'pending',
      },
      {
        id: 'm3',
        title: 'Testing',
        description: 'Data integrity testing',
        status: 'pending',
      },
      {
        id: 'm4',
        title: 'Deployment',
        description: 'Go-live and monitoring setup',
        status: 'pending',
      },
    ],
    deliverables: [
      {
        id: 'd1',
        name: 'Sync Workflow Package',
        type: 'workflow',
        url: '/files/sync-workflow.json',
        locked: true,
      },
    ],
    feedback: [],
    createdAt: '2025-01-06T00:00:00Z',
    updatedAt: '2025-01-08T08:00:00Z',
    revisionCount: 0,
  },
];

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'Project Ready',
    message: 'Lead Nurturing Sequence is ready for download!',
    read: false,
    createdAt: '2025-01-08T12:00:00Z',
    projectId: '2',
  },
  {
    id: '2',
    title: 'Milestone Completed',
    message: 'Core Workflow Development milestone completed',
    read: true,
    createdAt: '2025-01-06T15:30:00Z',
    projectId: '1',
  },
  {
    id: '3',
    title: 'New Feedback',
    message: 'Sarah responded to your feedback on Order Automation',
    read: true,
    createdAt: '2025-01-05T11:45:00Z',
    projectId: '1',
  },
];
